-- ==============================
-- RPC / FUNCTIONS
-- ==============================

[
  {
    "definition": "CREATE OR REPLACE FUNCTION public.review_exam_by_id(p_exam_id bigint)\n RETURNS json\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nDECLARE\r\n  v_role text;\r\nBEGIN\r\n\r\n  SELECT role INTO v_role\r\n  FROM profiles\r\n  WHERE id = auth.uid();\r\n\r\n  IF v_role NOT IN ('teacher','admin') THEN\r\n    RAISE EXCEPTION 'Permission denied';\r\n  END IF;\r\n\r\n  RETURN (\r\n    SELECT row_to_json(e)\r\n    FROM exams e\r\n    WHERE e.id = p_exam_id\r\n  );\r\n\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.list_user_exams(p_user_id uuid)\n RETURNS json\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nDECLARE\r\n  v_role text;\r\nBEGIN\r\n\r\n  SELECT role INTO v_role\r\n  FROM profiles\r\n  WHERE id = auth.uid();\r\n\r\n  IF v_role NOT IN ('teacher','admin') THEN\r\n    RAISE EXCEPTION 'Permission denied';\r\n  END IF;\r\n\r\n  RETURN (\r\n    SELECT json_agg(row_to_json(e))\r\n    FROM exams e\r\n    WHERE e.user_id = p_user_id\r\n  );\r\n\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.get_my_role()\n RETURNS user_role\n LANGUAGE sql\n STABLE SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\n  SELECT role\r\n  FROM public.profiles\r\n  WHERE id = auth.uid()\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.handle_new_user()\n RETURNS trigger\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nbegin\r\n  insert into public.profiles (id)\r\n  values (new.id);\r\n  return new;\r\nend;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.update_mcq_question(p_question_id bigint, p_question_text text, p_explanation text, p_question_type_id integer, p_difficulty integer, p_grade_level integer, p_options jsonb)\n RETURNS json\n LANGUAGE plpgsql\nAS $function$\r\ndeclare\r\n  v_option jsonb;\r\n  v_correct_count int := 0;\r\nbegin\r\n\r\n  -- Check question exists\r\n  if not exists (\r\n    select 1\r\n    from questions\r\n    where id = p_question_id\r\n      and is_active = true\r\n  ) then\r\n    raise exception 'Question not found or inactive';\r\n  end if;\r\n\r\n  -- Validate options count\r\n  if jsonb_array_length(p_options) < 2 then\r\n    raise exception 'MCQ must have at least 2 options';\r\n  end if;\r\n\r\n  -- Count correct answers\r\n  for v_option in\r\n    select * from jsonb_array_elements(p_options)\r\n  loop\r\n    if (v_option->>'is_correct')::boolean then\r\n      v_correct_count := v_correct_count + 1;\r\n    end if;\r\n  end loop;\r\n\r\n  if v_correct_count <> 1 then\r\n    raise exception 'MCQ must have exactly 1 correct answer';\r\n  end if;\r\n\r\n  -- Update question\r\n  update questions\r\n  set\r\n    question_text = p_question_text,\r\n    explanation = p_explanation,\r\n    question_type_id = p_question_type_id,\r\n    difficulty = p_difficulty,\r\n    grade_level = p_grade_level\r\n  where id = p_question_id;\r\n\r\n  -- Replace options\r\n  delete from options\r\n  where question_id = p_question_id;\r\n\r\n  for v_option in\r\n    select * from jsonb_array_elements(p_options)\r\n  loop\r\n    insert into options (\r\n      question_id,\r\n      option_label,\r\n      option_text,\r\n      is_correct\r\n    )\r\n    values (\r\n      p_question_id,\r\n      v_option->>'option_label',\r\n      v_option->>'option_text',\r\n      (v_option->>'is_correct')::boolean\r\n    );\r\n  end loop;\r\n\r\n  return json_build_object(\r\n    'message', 'Question updated successfully',\r\n    'question_id', p_question_id\r\n  );\r\n\r\nexception\r\n  when others then\r\n    raise exception 'Update transaction failed: %', sqlerrm;\r\nend;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.create_mcq_question(p_question_text text, p_explanation text, p_question_type_id integer, p_difficulty integer, p_grade_level integer, p_options jsonb)\n RETURNS json\n LANGUAGE plpgsql\nAS $function$\r\ndeclare\r\n  v_question_id int;\r\n  v_option jsonb;\r\nbegin\r\n  -- Insert question\r\n  insert into questions (\r\n    question_text,\r\n    explanation,\r\n    question_type_id,\r\n    difficulty,\r\n    grade_level,\r\n    is_active\r\n  )\r\n  values (\r\n    p_question_text,\r\n    p_explanation,\r\n    p_question_type_id,\r\n    p_difficulty,\r\n    p_grade_level,\r\n    true\r\n  )\r\n  returning id into v_question_id;\r\n\r\n  -- Insert options\r\n  for v_option in select * from jsonb_array_elements(p_options)\r\n  loop\r\n    insert into options (\r\n      question_id,\r\n      option_label,\r\n      option_text,\r\n      is_correct\r\n    )\r\n    values (\r\n      v_question_id,\r\n      v_option->>'option_label',\r\n      v_option->>'option_text',\r\n      (v_option->>'is_correct')::boolean\r\n    );\r\n  end loop;\r\n\r\n  return json_build_object(\r\n    'message', 'Question created successfully',\r\n    'question_id', v_question_id\r\n  );\r\n\r\nexception\r\n  when others then\r\n    raise exception 'Transaction failed: %', sqlerrm;\r\nend;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.generate_exam(p_grade_level integer, p_structure jsonb)\n RETURNS json\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nDECLARE\r\n  v_exam_id bigint;\r\n  v_type_id text;\r\n  v_limit integer;\r\n  v_question_id bigint;\r\n  v_order integer := 1;\r\n  v_user_id uuid := auth.uid();\r\nBEGIN\r\n\r\n  IF v_user_id IS NULL THEN\r\n    RAISE EXCEPTION 'Not authenticated';\r\n  END IF;\r\n\r\n  -- chỉ student được tạo exam\r\n  IF NOT EXISTS (\r\n    SELECT 1 FROM profiles\r\n    WHERE id = v_user_id\r\n    AND role = 'student'\r\n  ) THEN\r\n    RAISE EXCEPTION 'Only student can generate exam';\r\n  END IF;\r\n\r\n  -- không cho tạo nếu còn exam chưa submit\r\n  IF EXISTS (\r\n    SELECT 1 FROM exams\r\n    WHERE user_id = v_user_id\r\n    AND submitted_at IS NULL\r\n  ) THEN\r\n    RAISE EXCEPTION 'Unsubmitted exam exists';\r\n  END IF;\r\n\r\n  INSERT INTO exams (\r\n    user_id,\r\n    grade_level,\r\n    total_questions\r\n  )\r\n  VALUES (\r\n    v_user_id,\r\n    p_grade_level,\r\n    0\r\n  )\r\n  RETURNING id INTO v_exam_id;\r\n\r\n  FOR v_type_id, v_limit IN\r\n    SELECT key, value::integer\r\n    FROM jsonb_each(p_structure)\r\n  LOOP\r\n\r\n    FOR v_question_id IN\r\n      SELECT id\r\n      FROM questions\r\n      WHERE question_type_id = v_type_id::bigint\r\n      AND grade_level = p_grade_level\r\n      AND is_active = true\r\n      ORDER BY random()\r\n      LIMIT v_limit\r\n    LOOP\r\n\r\n      INSERT INTO exam_questions (\r\n        exam_id,\r\n        question_id,\r\n        question_order\r\n      )\r\n      VALUES (\r\n        v_exam_id,\r\n        v_question_id,\r\n        v_order\r\n      );\r\n\r\n      v_order := v_order + 1;\r\n\r\n    END LOOP;\r\n\r\n  END LOOP;\r\n\r\n  UPDATE exams\r\n  SET total_questions = v_order - 1\r\n  WHERE id = v_exam_id;\r\n\r\n  RETURN json_build_object(\r\n    'exam_id', v_exam_id,\r\n    'total_questions', v_order - 1\r\n  );\r\n\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.prevent_answer_after_submit()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Không cho đổi exam_id\r\n    IF TG_OP = 'UPDATE' AND NEW.exam_id <> OLD.exam_id THEN\r\n        RAISE EXCEPTION 'Cannot change exam reference';\r\n    END IF;\r\n\r\n    -- Không cho sửa nếu exam đã submit\r\n    IF EXISTS (\r\n        SELECT 1\r\n        FROM public.exams\r\n        WHERE id = NEW.exam_id\r\n        AND submitted_at IS NOT NULL\r\n    ) THEN\r\n        RAISE EXCEPTION 'Exam already submitted';\r\n    END IF;\r\n\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.prevent_exam_update_after_submit()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    IF OLD.submitted_at IS NOT NULL THEN\r\n        RAISE EXCEPTION 'Cannot modify submitted exam';\r\n    END IF;\r\n\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.prevent_delete_submitted_exam()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    IF OLD.submitted_at IS NOT NULL THEN\r\n        RAISE EXCEPTION 'Cannot delete submitted exam';\r\n    END IF;\r\n\r\n    RETURN OLD;\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.prevent_question_delete()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    RAISE EXCEPTION 'Hard delete not allowed. Use soft delete.';\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.submit_exam(p_exam_id bigint)\n RETURNS json\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nDECLARE\r\n  v_user_id uuid := auth.uid();\r\n  v_score integer;\r\n  v_total integer;\r\nBEGIN\r\n\r\n  IF v_user_id IS NULL THEN\r\n    RAISE EXCEPTION 'Not authenticated';\r\n  END IF;\r\n\r\n  -- kiểm tra exam thuộc user và chưa submit\r\n  IF NOT EXISTS (\r\n    SELECT 1\r\n    FROM exams\r\n    WHERE id = p_exam_id\r\n      AND user_id = v_user_id\r\n      AND submitted_at IS NULL\r\n  ) THEN\r\n    RAISE EXCEPTION 'Exam not found or already submitted';\r\n  END IF;\r\n\r\n  -- cập nhật is_correct cho user_answers (tránh tính lại nhiều lần sau này)\r\n  UPDATE user_answers ua\r\n  SET is_correct = o.is_correct\r\n  FROM options o\r\n  WHERE ua.selected_option_id = o.id\r\n    AND ua.exam_id = p_exam_id;\r\n\r\n  -- tính điểm\r\n  SELECT COUNT(*) INTO v_score\r\n  FROM user_answers\r\n  WHERE exam_id = p_exam_id\r\n    AND is_correct = true;\r\n\r\n  -- lấy tổng câu\r\n  SELECT total_questions INTO v_total\r\n  FROM exams\r\n  WHERE id = p_exam_id;\r\n\r\n  -- cập nhật exam\r\n  UPDATE exams\r\n  SET\r\n    submitted_at = now(),\r\n    score = v_score\r\n  WHERE id = p_exam_id;\r\n\r\n  RETURN json_build_object(\r\n    'exam_id', p_exam_id,\r\n    'score', v_score,\r\n    'total_questions', v_total\r\n  );\r\n\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.get_my_active_exam()\n RETURNS json\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nDECLARE\r\n  v_user_id uuid := auth.uid();\r\n  v_exam_id bigint;\r\nBEGIN\r\n\r\n  IF v_user_id IS NULL THEN\r\n    RAISE EXCEPTION 'Not authenticated';\r\n  END IF;\r\n\r\n  SELECT id INTO v_exam_id\r\n  FROM exams\r\n  WHERE user_id = v_user_id\r\n    AND submitted_at IS NULL\r\n  LIMIT 1;\r\n\r\n  IF v_exam_id IS NULL THEN\r\n    RETURN NULL;\r\n  END IF;\r\n\r\n  RETURN json_build_object(\r\n    'exam_id', v_exam_id\r\n  );\r\n\r\nEND;\r\n$function$\n"
  },
  {
    "definition": "CREATE OR REPLACE FUNCTION public.review_my_exam(p_exam_id bigint)\n RETURNS json\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nDECLARE\r\n  v_user_id uuid := auth.uid();\r\nBEGIN\r\n\r\n  IF NOT EXISTS (\r\n    SELECT 1 FROM exams\r\n    WHERE id = p_exam_id\r\n      AND user_id = v_user_id\r\n      AND submitted_at IS NOT NULL\r\n  ) THEN\r\n    RAISE EXCEPTION 'Exam not found';\r\n  END IF;\r\n\r\n  RETURN (\r\n    SELECT json_agg(row_to_json(t))\r\n    FROM (\r\n      SELECT\r\n        q.id AS question_id,\r\n        ua.selected_option_id,\r\n        ua.is_correct,\r\n        o_correct.id AS correct_option_id\r\n      FROM exam_questions eq\r\n      JOIN questions q ON q.id = eq.question_id\r\n      LEFT JOIN user_answers ua\r\n        ON ua.exam_id = p_exam_id\r\n       AND ua.question_id = q.id\r\n      LEFT JOIN options o_correct\r\n        ON o_correct.question_id = q.id\r\n       AND o_correct.is_correct = true\r\n      WHERE eq.exam_id = p_exam_id\r\n      ORDER BY eq.question_order\r\n    ) t\r\n  );\r\n\r\nEND;\r\n$function$\n"
  }
]